CREATE TABLE IF NOT EXISTS products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    good_id text NOT NULL UNIQUE,
    sku text NOT NULL,
    winspeed text,
    model text,
    product_url text,
    image_url text,
    image_status text NOT NULL DEFAULT 'missing' CHECK (image_status IN ('available','missing','broken')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS products_sku_idx ON products(sku);
CREATE INDEX IF NOT EXISTS products_winspeed_idx ON products(winspeed);
CREATE INDEX IF NOT EXISTS products_model_idx ON products(model);
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
-- Only the trusted backend database role accesses this table in Phase 2.
