-- Migration 002: Add Shopify cost/catalog fields and sync logs table
-- Backward-compatible with Phase 1/Phase 2 products table

ALTER TABLE products ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS vendor text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS product_type text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS tags text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS part_type text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS power_type text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS spapart_or_product text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS inventory_quantity integer;
ALTER TABLE products ADD COLUMN IF NOT EXISTS price text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS compare_at_price text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS last_sync_at timestamptz;

CREATE TABLE IF NOT EXISTS sync_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_source text NOT NULL DEFAULT 'shopify',
    status text NOT NULL,
    rows_synced integer DEFAULT 0,
    started_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    error_message text
);

CREATE INDEX IF NOT EXISTS sync_logs_started_at_idx ON sync_logs(started_at DESC);
ALTER TABLE sync_logs ENABLE ROW LEVEL SECURITY;
