import {test, expect} from '@playwright/test';
import path from 'node:path';
import fs from 'node:fs';
import type {Quotation} from '../src/lib/api';

test('upload, drag, resize, zoom, paste an image and export saved positions', async ({page,context})=> {
  const errors:string[]=[];
  page.on('pageerror', error=>errors.push(error.message));
  await page.goto('/');
  const uploaded=page.waitForResponse(r=>r.url().endsWith('/api/quotations')&&r.request().method()==='POST');
  await page.locator('input[accept="application/pdf,.pdf"]').setInputFiles(path.resolve('../../QT_test.pdf'));
  let quotation:Quotation=await (await uploaded).json();
  await expect(page.getByTestId('pdf-preview')).toHaveAttribute('data-rendered','true');
  await expect(page.getByTestId('image-overlay-0')).toBeVisible();
  const productImage=await context.request.get(quotation.items[1].image_url!);
  expect(productImage.status()).toBe(200);
  fs.writeFileSync('../../tmp/editor-product.jpg',await productImage.body());
  await page.getByRole('button',{name:'อัปโหลดรูป',exact:true}).click();
  const replacement=page.waitForResponse(r=>r.url().includes('/items/0/image')&&r.request().method()==='POST');
  await page.getByLabel('เลือกรูปจากเครื่อง').setInputFiles(path.resolve('../../tmp/editor-product.jpg'));
  quotation=await (await replacement).json();
  expect(quotation.items[0].uploaded_image).toBe(true);
  await expect(page.getByRole('button',{name:'ย่อรูป',exact:true})).toBeEnabled();
  const shrink=page.waitForResponse(r=>r.url().endsWith('/items/0/placement')&&r.request().method()==='PUT');
  await page.getByRole('button',{name:'ย่อรูป',exact:true}).click();
  quotation=await (await shrink).json();
  const original=quotation.items[0].placement!;
  await expect(page.getByRole('button',{name:'ซูมเข้า',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'ซูมเข้า',exact:true}).click();
  await expect(page.getByText('125%',{exact:true})).toBeVisible();
  const overlay=page.getByTestId('image-overlay-0');
  await overlay.scrollIntoViewIfNeeded();
  const before=(await overlay.boundingBox())!;
  const pageWidth=before.width/original.width;
  const moved=page.waitForResponse(r=>r.url().endsWith('/items/0/placement')&&r.request().method()==='PUT');
  await page.mouse.move(before.x+before.width/2,before.y+before.height/2);
  await page.mouse.down();
  await page.mouse.move(before.x+before.width/2+8,before.y+before.height/2+5,{steps:8});
  await page.mouse.up();
  const movedResponse=await moved;
  expect(movedResponse.status()).toBe(200);
  quotation=await movedResponse.json();
  expect(quotation.items[0].placement!.x-original.x).toBeCloseTo(8/pageWidth,3);
  await expect(page.getByRole('button',{name:'ขยายรูป',exact:true})).toBeEnabled();
  const handle=page.getByTestId('resize-handle');
  const corner=(await handle.boundingBox())!;
  const resized=page.waitForResponse(r=>r.url().endsWith('/items/0/placement')&&r.request().method()==='PUT');
  await page.mouse.move(corner.x+corner.width/2,corner.y+corner.height/2);
  await page.mouse.down();
  await page.mouse.move(corner.x+corner.width/2-4,corner.y+corner.height/2-4,{steps:6});
  await page.mouse.up();
  const resizedResponse=await resized;
  expect(resizedResponse.status()).toBe(200);
  quotation=await resizedResponse.json();
  expect(quotation.items[0].placement!.width).toBeLessThan(original.width);
  await expect(page.getByRole('button',{name:'2. DB-CW76-DRG',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'2. DB-CW76-DRG',exact:true}).click();
  await context.grantPermissions(['clipboard-read','clipboard-write']);
  const normalizedImage=await context.request.get(quotation.items[0].image_url!);
  const png=(await normalizedImage.body()).toString('base64');
  await page.evaluate(async base64=>{
    const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0));
    await navigator.clipboard.write([new ClipboardItem({'image/png':new Blob([bytes],{type:'image/png'})})]);
  },png);
  const pasted=page.waitForResponse(r=>r.url().includes('/items/1/image')&&r.request().method()==='POST');
  await page.keyboard.press('Control+V');
  const pasteResponse=await pasted;
  expect(pasteResponse.status()).toBe(200);
  quotation=await pasteResponse.json();
  expect(quotation.items[1].uploaded_image).toBe(true);
  await expect(page.getByRole('button',{name:'ซูมออก',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'ซูมออก',exact:true}).click();
  const generated=page.waitForResponse(r=>r.url().endsWith('/generate')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'สร้าง PDF โดยข้ามรูปที่ยังไม่มี'}).click();
  quotation=await (await generated).json();
  expect(quotation.images_inserted).toBe(18);
  await expect(page.getByText('PDF พร้อมดาวน์โหลด',{exact:true})).toBeVisible();
  await page.getByTestId('pdf-preview').scrollIntoViewIfNeeded();
  await page.screenshot({path:'../../tmp/image-editor-desktop.png',fullPage:true,animations:'disabled'});
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('link',{name:'ดาวน์โหลด PDF'}).click();
  const download=await downloadPromise;
  await download.saveAs('../../tmp/image-editor-export.pdf');
  fs.writeFileSync('../../tmp/image-editor-layout.json',JSON.stringify(quotation));
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'../../tmp/image-editor-mobile.png',fullPage:true,animations:'disabled'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
